# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Recall < Formula
  desc "A CLI tool to find commands by describing what you want to do when you forget them"
  homepage "https://github.com/spider-hand/recall"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spider-hand/recall/releases/download/v1.0.2/recall_1.0.2_darwin_amd64.tar.gz"
      sha256 "b26e7d8756112f0895b33207b5c98e54ba62aa7c59a0b84aa26cc913df9a60bd"

      define_method(:install) do
        bin.install "recall"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spider-hand/recall/releases/download/v1.0.2/recall_1.0.2_darwin_arm64.tar.gz"
      sha256 "cdb840a7e052765035481423aa59dc6d693bda8e60fcde44862bc4d3736e3ee9"

      define_method(:install) do
        bin.install "recall"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spider-hand/recall/releases/download/v1.0.2/recall_1.0.2_linux_amd64.tar.gz"
      sha256 "e1bade37db1f538400c4447bb66f6a6f599671080136baaba35383cd63145470"
      define_method(:install) do
        bin.install "recall"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spider-hand/recall/releases/download/v1.0.2/recall_1.0.2_linux_arm64.tar.gz"
      sha256 "a86d5cd814cd3074aaae599a3f689289fcf422756eb2761fc9117e1d4a33ce0e"
      define_method(:install) do
        bin.install "recall"
      end
    end
  end

  test do
    system "#{bin}/recall", "--version"
  end
end
